name: glucotrack_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  path: ^1.9.0
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/navbar/
    - assets/
    - .env
