name: glucotrack_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  path: ^1.9.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/navbar/
    - assets/
    - .env
    - assets/profile/
    - assets/article/
